// Generated by CoffeeScript 2.2.2
(function() {
  // just test env.
  var assert;

  assert = require('assert');

  describe('target is check enviroment about tdd(mocha)', function() {
    return it('one should equal one::', function() {
      return assert.equal(1, 0 + 1);
    });
  });

}).call(this);
