// Generated by CoffeeScript 2.3.2
(function() {
  // 2019-2
  var Account, NohmModel;

  ({NohmModel} = require('nohm'));

  Account = (function() {
    class Account extends NohmModel {};

    Account.modelName = 'account';

    Account.idGenerator = 'increment';

    Account.definitions = {
      name: {
        type: 'string',
        index: true,
        validations: [
          'notEmpty',
          {
            name: 'length',
            options: {
              min: 4,
              max: 15
            }
          },
          // granttee that name not contains '0' or 'o',they are not clear
          // display on screen,always.
          function(value,
          options) {
            return Promise.resolve(!/[0o]/.test(value));
          }
        ]
      },
      code: {
        type: 'integer',
        index: true,
        validations: ['notEmpty']
      },
      password: {
        type: 'string',
        validations: ['notEmpty']
      },
      timestamp: {
        type: 'string',
        index: true
      },
      alive: {
        type: 'boolean',
        validations: ['notEmpty'],
        defaultValue: true
      }
    };

    return Account;

  }).call(this);

  module.exports = Account;

}).call(this);
