// Generated by CoffeeScript 2.3.1
(function() {
  var Admin, _parse, pug;

  pug = require('pug');

  Admin = (function() {
    class Admin {
      static mod2view(modelClass) {
        var abc, definitions, firstkey;
        abc = 'form.form-horizontal\n  .form-group\n    label(for= \'id\' + field_label)= field_label \n    input(type=field_type id= \'id\' + field_label class="form-control" placeholder="you know..")\n  .form-group\n    button(class="sumbmit") Submit!';
        definitions = modelClass.getDefinitions();
        firstkey = Object.keys(definitions)[0];
        console.log(pug.render(abc, {
          field_label: firstkey,
          field_type: definitions.title.type
        }));
        return pug.render(abc, {
          field_label: firstkey,
          field_type: definitions.title.type
        });
      }

    };

    Admin.version = '1.0';

    return Admin;

  }).call(this);

  
  // a help func - _parse
  _parse = function(definition) {
    // quantete the format of 'definition' object
    // we need output like this format:
    //   [{type:'string',TODO
    return null;
  };

  module.exports = Admin;

}).call(this);
