// Generated by CoffeeScript 2.3.2
(function() {
  var Account, NohmModel;

  ({NohmModel} = require('nohm'));

  Account = (function() {
    class Account extends NohmModel {};

    Account.modelName = 'account';

    Account.idGenerator = 'increment';

    Account.definitions = {
      name: {
        type: 'string',
        unique: true,
        validations: [
          'notEmpty',
          {
            name: 'length',
            options: {
              min: 4,
              max: 15
            }
          }
        ]
      },
      // Just a sample.below:
      // granttee that name not contains '0' or 'o',they are not clear
      // display on screen,always.
      //(value,options)->
      //  return Promise.resolve not /[0o]/.test value
      role: {
        type: 'integer',
        index: true,
        validations: [
          'notEmpty',
          function(val) {
            return Promise.resolve(val === 'admin' || val === 'superuser' || val === 'user' || val === 'unknown');
          }
        ]
      },
      password: {
        type: 'string',
        validations: ['notEmpty']
      },
      initial_timestamp: {
        type: 'integer',
        validations: ['notEmpty'],
        index: true
      },
      alive: {
        type: 'boolean',
        validations: ['notEmpty'],
        defaultValue: true
      }
    };

    return Account;

  }).call(this);

  module.exports = Account;

}).call(this);
