// Generated by CoffeeScript 2.3.2
(function() {
  var Daka, NohmModel;

  ({NohmModel} = require('nohm'));

  Daka = (function() {
    class Daka extends NohmModel {};

    Daka.modelName = 'daily';

    Daka.idGenerator = 'increment';

    Daka.definitions = {
      alias: {
        type: 'string',
        validations: ['notEmpty'],
        index: true
      },
      utc_ms: {
        type: 'integer',
        validations: ['notEmpty'],
        index: true
      },
      browser: {
        type: 'string'
      },
      whatistime: {
        type: 'string',
        validations: ['notEmpty']
      },
      isProxy: {
        type: 'boolean',
        validations: ['notEmpty'],
        defaultValue: false
      },
      category: {
        type: 'string',
        validations: [
          'notEmpty',
          function(value,
          options) {
            return Promise.resolve(value === 'am' || value === 'AM' || value === 'pm' || value === 'PM');
          }
        ]
      }
    };

    return Daka;

  }).call(this);

  module.exports = Daka;

}).call(this);
