// Generated by CoffeeScript 2.3.2
(function() {
  var Daka, NohmModel;

  ({NohmModel} = require('nohm'));

  Daka = (function() {
    class Daka extends NohmModel {};

    Daka.modelName = 'daily';

    Daka.idGenerator = 'increment';

    Daka.definitions = {
      name: {
        type: 'string',
        index: true,
        validations: ['notEmpty']
      },
      code: {
        type: 'integer',
        index: true,
        validations: ['notEmpty']
      }
    };

    return Daka;

  }).call(this);

  module.exports = Daka;

}).call(this);
