// Generated by CoffeeScript 2.2.2
(function() {
  var express, router, spawn;

  express = require('express');

  router = express.Router();

  ({spawn} = require('child_process'));

  router.get('/tool-1', function(req, res, next) {
    return res.send('hi,i am tool No.1');
  });

  router.get('/flushdb', function(req, res, next) {
    return res.send('i am ready to flush db.');
  });

  router.get('/savenow', function(req, res, next) {
    var savenow;
    // redis-cli is a link,live in "/usr/bin/"
    // ignores secure things,like authenticate and session,cookie
    savenow = spawn('redis-cli', ['save']);
    return savenow.on('close', function(code) {
      if ((parseInt(code)) !== 0) {
        return res.render('hasntsaved');
      } else {
        return res.render('hassaved');
      }
    });
  });

  module.exports = router;

}).call(this);
