// Generated by CoffeeScript 2.2.2
(function() {
  var express, router;

  express = require('express');

  router = express.Router();

  router.get('/tool-1', function(req, res, next) {
    return res.send('hi,i am tool No.1');
  });

  module.exports = router;

}).call(this);
