// Generated by CoffeeScript 2.3.1
(function() {
  var express, fs, path, router;

  path = require('path');

  fs = require('fs');

  express = require('express');

  router = express.Router();

  // test for initial level
  router.get('/alpha-1', function(req, res, next) {
    return res.send('hi,i am alpha No.1');
  });

  router.get('/indexeddb', function(req, res, next) {
    // see safari or firefox window.indexeddb attribute
    return res.render('alpha/indexeddb.pug');
  });

  router.get('/*', function(req, res, next) {
    var abs, extname;
    abs = path.join(path.dirname(__dirname), 'views', req.path);
    extname = path.extname(abs);
    if (!fs.existsSync(abs)) {
      return next();
    } else {
      if (extname.toLowerCase() === '.pug') {
        return res.render(req.path.substr(1));
      } else if (extname.toLowerCase() === '.html') {
        return res.sendFile(abs);
      } else {
        console.log(extname);
        return res.send('not clear mime type.');
      }
    }
  });

  module.exports = router;

}).call(this);
