// Generated by CoffeeScript 2.2.2
(function() {
  var Browser, app, browser, http;

  Browser = require('zombie');

  Browser.localhost('example.com', 4140);

  browser = new Browser;

  app = require('../app');

  http = require('http');

  http.Server(app);

  app.listen(4140);

  // sometimes it will help(below line)
  //browser.waitDuration = '30s'
  describe('zombie ability display::', function() {
    return describe('access index page should success::', function() {
      before(function() {
        return browser.visit('http://example.com');
      });
      it('should access page successfully::', function() {
        return browser.assert.success();
      });
      //No Need This Time
      //console.log browser.html()
      it('should has 2 h4 tags::', function() {
        return browser.assert.elements('h4', 2);
      });
      return it('page title is "I see You"::', function() {
        return browser.assert.text('title', 'I see You');
      });
    });
  });

}).call(this);
