// Generated by CoffeeScript 2.2.2
(function() {
  // just test zombie + mocha enviroment
  var Browser, app, browser, http, server;

  http = require('http');

  app = require('../app.js');

  server = http.Server(app);

  server.listen(3004, 'localhost');

  Browser = require('zombie');

  Browser.localhost('example.com', 3004); //3003 is development specail port

  browser = new Browser;

  describe('access site index page is easy::', function() {
    before(function(done) {
      return browser.visit('example.com', done);
    });
    it('should access page successfully::', function() {
      return browser.assert.success();
    });
    return it('page title is "you see you"::', function() {
      return browser.assert.text('title', 'I see you');
    });
  });

}).call(this);
